name: Reusable Java Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        working-directory: complete
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: complete/target/*.jar